---
- name: Install stunnel4
  with_items:
    - stunnel4

  apt: name={{ item }} state=present

- name: Configure stunnel4
  template: src=stunnel4.conf.j2 dest=/etc/stunnel/stunnel.conf

- name: Enable stunnel
  lineinfile: dest=/etc/default/stunnel4 regexp=^ENABLED line=ENABLED=1
  
- name: Stop stunnel4
  service: name=stunnel4 state=stopped
  
- name: Start stunnel4
  notify:
    - start stunnel4
  service: name=stunnel4 enabled=yes state=started 
  
